parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: note
    database_user: note
    database_password: zras2ACW2BSep2A5
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: aef1e7bc90c1d783a104e6d3897c2debc
    database_path: null