_welcome:
    pattern:  /welcome
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml


acme_main_homepage:
    pattern:  /
    defaults: { _controller: AcmeMainBundle:Default:index }

login:
    pattern:   /login
    defaults:  { _controller: AcmeSecurityBundle:Default:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

registration: 
    pattern: /registration
    defaults: { _controller: AcmeSecurityBundle:Default:registration }

test:
    pattern: /test
    defaults: { _controller: AcmeMainBundle:Test:index }



get_note:
    pattern:  /notes/get_note
    defaults: { _controller: AcmeMainBundle:Notes:getNote }
    requirements:
        _method:  POST

get_dir:
    pattern:  /notes/get_dir
    defaults: { _controller: AcmeMainBundle:Notes:getDir }
    requirements:
        _method:  POST

get_nav_list: 
    pattern: /notes/get_nav_list
    defaults: { _controller: AcmeMainBundle:Notes:getNavList }
    requirements:
        _method: POST

get_breadcrumbs:
    pattern: /notes/get_breadcrumbs
    defaults: { _controller: AcmeMainBundle:Notes:getBreadcrumbs }
    requirements: 
        _method: POST

save_note:
    pattern: /notes/save_note
    defaults: { _controller: AcmeMainBundle:Notes:saveNote }
    requirements: 
        _method: POST

save_dir:
    pattern: /notes/save_dir
    defaults: { _controller: AcmeMainBundle:Notes:saveDir }
    requirements: 
        _method: POST

save_nav_list:
    pattern:  /notes/save_nav_list
    defaults: { _controller: AcmeMainBundle:Notes:saveNavList }
    requirements:
        _method:  POST

delete:
    pattern: /notes/delete
    defaults: { _controller: AcmeMainBundle:Notes:delete }
    requirements: 
        _method: POST

paste:
    pattern: /notes/paste
    defaults: { _controller: AcmeMainBundle:Notes:paste }
    requirements: 
        _method: POST

notes: 
    pattern: /notes/
    defaults: { _controller: AcmeMainBundle:Notes:index}

notes_hash: 
    pattern: /notes/{hash}
    defaults: { _controller: AcmeMainBundle:Notes:index}
    requirements:
        hash: "[\w\/]{0,}"

profile: 
    pattern: /profile/
    defaults: { _controller: AcmeMainBundle:Profile:index}