jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:

        Acme\ModelBundle\Entity\User:
            algorithm:        sha512
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Acme\ModelBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /
                check_path:  /login_check

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reg_apply$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w+, roles: ROLE_USER }
